name: 'update'
on:
  push:
    branches:
      - 'test'
  schedule:
    - cron: 0/5 * * * *
jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
      - name: 'update'
        run: cd scripts && yarn add axios && node ./autoUpdate.js
      - name: 'show packs'
        run: cat packages.json
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.SSH_kEY }}
